name: front-end ESLint

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: Run ESLint on front-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .